service: tic-tac-toe-serverless-demo

provider:
  name: aws
  runtime: nodejs8.10
  stage: local
  region: us-east-1
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

package:
  exclude:
    - .git

functions:

  create-game:
    handler: src/functions/create-game.handler

  get-game-state:
    handler: src/functions/get-game-state.handler

  list-games:
    handler: src/functions/list-games.handler
    events:
      - http:
          path: /games
          method: get
          integration: lambda

  play:
    handler: functions/play.handler

plugins:
  - serverless-dynamodb-local
  - serverless-offline
