service: tic-tac-toe-serverless-demo

provider:
  name: aws
  runtime: nodejs8.10
  stage: local
  region: us-east-1
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}

package:
  exclude:
    - .git

functions:

  create-game:
    handler: src/functions/create-game.handler
    events:
      - http:
          path: /games
          method: post
          integration: lambda

  get-game:
    handler: src/functions/get-game.handler
    events:
      - http:
          path: /games/{gameId}
          method: get
          integration: lambda

  list-games:
    handler: src/functions/list-games.handler
    events:
      - http:
          path: /games
          method: get
          integration: lambda

  play:
    handler: src/functions/play.handler
    events:
      - http:
          path: /games/{gameId}
          method: post
          integration: lambda

plugins:
  - serverless-dynamodb-local
  - serverless-offline
